### ISSUE TITLE
Error when installing the requirements

### ISSUE THREAD

**Issue by AngieC96** [ginevracoal/statistical-machine-learning#2]
Hi,

I tried to follow all the steps you put on the readme, but when trying to install all the requirements via the file `requirements.txt` with the command `pip3 install -r requirements.txt` I get the following error:

```{bash}
ERROR: Invalid requirement: 'Package            Version' (from line 1 of requirements.txt)
```

I hope you can help me, thank you very much!

**Comment by ginevracoal** [comment]
Sorry I made a silly mistake! It should work now (I just updated
requirements.txt), let me know.

Ginevra

Il giorno ven 13 mar 2020 alle ore 18:39 Angela Carraro <
notifications@github.com> ha scritto:
