### ISSUE TITLE
Issue when installing futures requirement

### ISSUE THREAD

**Issue by eferos93** [ginevracoal/statistical-machine-learning#7]
Hello,

I am facing an error when installing the requirements `pip3 install -r requirements.txt` which looks like the following:
`ERROR: Could not find a version that satisfies the requirement futures==3.2.0 (from -r requirements.txt (line 13)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
`

My specs are
OS: Ubuntu 19.04
Python: 3.7.3

If you need any other information, please ask :).

Eros

**Comment by emaballarin** [comment]
Hi there!

Please, can you try if [this](https://raw.githubusercontent.com/emaballarin/statistical-machine-learning/minorfixes/requirements.txt) `requirements.txt` file does work? If that's the case, PR #6 should fix it.

**Comment by eferos93** [comment]
Worked! Thanks Emanuele :)
